kaif-web/src/main/java/io/kaif/model/debate/Debate.java
package io.kaif.model.debate;

import java.sql.Date;
import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

import javax.annotation.Nullable;

import com.google.common.base.Preconditions;

import io.kaif.flake.FlakeId;
import io.kaif.kmark.KmarkProcessor;
import io.kaif.model.account.Account;
import io.kaif.model.account.Authorization;
import io.kaif.model.article.Article;
import io.kaif.model.zone.Zone;
import io.kaif.web.v1.dto.V1DebateDto;

public class Debate {

  public static final FlakeId NO_PARENT = FlakeId.MIN;
  private static final int MAX_LEVEL = 10;
  public static final int CONTENT_MIN = 5;
  public static final int CONTENT_MAX = 4096;

  public static Debate create(Article article,
      FlakeId debateId,
      @Nullable Debate parent,
      String content,
      Account debater,
      Instant now) {
    Optional<Debate> optParent = Optional.ofNullable(parent);
    FlakeId parentId = optParent.map(Debate::getDebateId).orElse(NO_PARENT);
    int parentLevel = optParent.map(Debate::getLevel).orElse(0);
    UUID replyToAccountId = optParent.map(Debate::getDebaterId).orElseGet(article::getAuthorId);
    return new Debate(article.getArticleId(),
        debateId,
        article.getZone(),
        parentId,
        replyToAccountId,
        parentLevel + 1,
        content,
        DebateContentType.MARK_DOWN,
        debater.getAccountId(),
        debater.getUsername(),
        0,
        0,
        now,
        now);
  }

  public static String renderContentPreview(String rawContent) {
    return KmarkProcessor.process(rawContent);
  }

  private final FlakeId articleId;
  private final FlakeId debateId;
  private final Zone zone;
  private final FlakeId parentDebateId;
  private final int level;
  private final String content;
  private final DebateContentType contentType;
  private final UUID debaterId;
  private final String debaterName;
  private final long upVote;
  private final long downVote;
  private final Instant createTime;
  private final Instant lastUpdateTime;
  private final UUID replyToAccountId;

  Debate(FlakeId articleId,
      FlakeId debateId,
      Zone zone,
      FlakeId parentDebateId,
      UUID replyToAccountId,
      int level,
      String content,
      DebateContentType contentType,
      UUID debaterId,
      String debaterName,
      long upVote,
      long downVote,
      Instant createTime,
      Instant lastUpdateTime) {
    Preconditions.checkArgument(level <= MAX_LEVEL);
    Preconditions.checkArgument(!NO_PARENT.equals(debateId));
    this.zone = zone;
    this.articleId = articleId;
    this.debateId = debateId;
    this.parentDebateId = parentDebateId;
    this.replyToAccountId = replyToAccountId;
    this.level = level;
    this.content = content;
    this.contentType = contentType;
    this.debaterId = debaterId;
    this.debaterName = debaterName;
    this.upVote = upVote;
    this.downVote = downVote;
    this.createTime = createTime;
    this.lastUpdateTime = lastUpdateTime;
  }

  public FlakeId getArticleId() {
    return articleId;
  }

  public FlakeId getDebateId() {
    return debateId;
  }

  public FlakeId getParentDebateId() {
    return parentDebateId;
  }

  public boolean hasParent() {
    return !parentDebateId.equals(NO_PARENT);
  }

  public int getLevel() {
    return level;
  }

  public String getContent() {
    return content;
  }

  public DebateContentType getContentType() {
    return contentType;
  }

  public UUID getDebaterId() {
    return debaterId;
  }

  public String getDebaterName() {
    return debaterName;
  }

  public long getUpVote() {
    return upVote;
  }

  public long getDownVote() {
    return downVote;
  }

  public Instant getCreateTime() {
    return createTime;
  }

  public Instant getLastUpdateTime() {
    return lastUpdateTime;
  }

  public String getRenderContent() {
    return KmarkProcessor.process(content);
  }

  public String getEscapeContent() {
    return KmarkProcessor.escapeHtml(content);
  }

  public UUID getReplyToAccountId() {
    return replyToAccountId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }

    Debate debate = (Debate) o;

    if (!debateId.equals(debate.debateId)) {
      return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return debateId.hashCode();
  }

  @Override
  public String toString() {
    return "Debate{" +
        "articleId=" + articleId +
        ", debateId=" + debateId +
        ", zone=" + zone +
        ", parentDebateId=" + parentDebateId +
        ", level=" + level +
        ", content='" + content + '\'' +
        ", contentType=" + contentType +
        ", debaterId=" + debaterId +
        ", debaterName='" + debaterName + '\'' +
        ", upVote=" + upVote +
        ", downVote=" + downVote +
        ", createTime=" + createTime +
        ", lastUpdateTime=" + lastUpdateTime +
        ", replyToAccountId=" + replyToAccountId +
        '}';
  }

  public long getTotalVote() {
    return upVote - downVote;
  }

  public boolean isMaxLevel() {
    return level >= MAX_LEVEL;
  }

  public boolean isParent(Debate child) {
    return parentDebateId.equals(child.debateId);
  }

  public boolean canEdit(Authorization auth) {
    return auth.belongToAccount(debaterId);
  }

  public Debate withVote(long newUpVote, long newDownVote) {
    return new Debate(articleId,
        debateId,
        zone,
        parentDebateId,
        replyToAccountId,
        level,
        content,
        contentType,
        debaterId,
        debaterName,
        newUpVote,
        newDownVote,
        createTime,
        lastUpdateTime);
  }

  public V1DebateDto toV1Dto() {
    return new V1DebateDto(articleId.toString(),
        debateId.toString(),
        zone.value(),
        hasParent() ? parentDebateId.toString() : null,
        level,
        content,
        debaterName,
        upVote,
        downVote,
        Date.from(createTime),
        Date.from(lastUpdateTime));
  }

  public Zone getZone() {
    return zone;
  }

  public boolean isEdited() {
    return lastUpdateTime.isAfter(createTime);
  }

  public String getShortUrlPath() {
    return String.format("/d/%s", getDebateId());
  }
}

kaif-web/src/main/resources/templates/macros/aside.ftl
<#import "/spring.ftl" as spring />
<#import "url.ftl" as url />
<#import "util.ftl" as util/>

<#-- implicit variable zoneInfo -->
<#macro createArticle>
<div class="aside-card">
    <h4>張貼新文</h4>

    <div class="aside-card-box">
        <p>
            好文難尋，知音難遇。分享你發掘到的好文吧！
        </p>
        <a href="<@url.createArticleLink />"
           class="pure-button pure-button-primary create-button">
            <i class="fa fa-caret-right"></i> 分享新連結</a>
    </div>
    <div class="aside-card-box">
        <p>
            分享你的想法、提出你的質疑、說出你的困惑！
        </p>
        <a href="<@url.createArticleSpeak />"
           class="pure-button pure-button-primary create-button">
            <i class="fa fa-caret-right"></i> 我有話要說</a>
    </div>
</div>
</#macro>

<#macro createZone>
<div class="aside-card">
    <h4>成立新討論區</h4>

    <div class="aside-card-box">
        <p>
            你有一個別人都沒有的想法？你該試試創造一個新的領域！
        </p>
        <a href="/zone/create"
           class="pure-button pure-button-primary create-button">
            <i class="fa fa-caret-right"></i> 建立討論區</a>
    </div>
</div>
</#macro>

<#macro recommendZones zoneInfos>
<div class="aside-card aside-zone-list">
    <h4>熱門討論區</h4>

    <div class="aside-card-box">
        <ul>
            <#list zoneInfos as zoneInfo>
                <li>
                    <a class="plain" href="<@url.zone data=zoneInfo/>">
                        <@url.zone data=zoneInfo/> - ${zoneInfo.aliasName}
                    </a>
                </li>
            </#list>
        </ul>
    </div>
</div>
</#macro>

<#-- data is username -->
<#macro administrators data>
<div class="aside-card aside-user-list">
    <h4>版主群</h4>

    <div class="aside-card-box">
        <ul>
            <#list data as username>
                <li>
                    <a class="plain" href="/u/${username}">
                        /u/${username}
                    </a>
                </li>
            </#list>
        </ul>
    </div>
</div>
</#macro>


<#-- data can be Debate or Article -->
<#macro shortUrl data>
<div class="aside-card aside-short-url">
    <h4>短網址</h4>

    <div class="aside-card-box">
        <input short-url-input type="text" value="http://kaif.io${data.shortUrlPath}">
    </div>
</div>
</#macro>

<#macro search>
<div class="aside-card">
    <h4>站內搜尋</h4>

    <div class="aside-card-box">
        <form class="pure-form search-form" action="https://www.google.com/cse/publicurl">
            <input type="hidden" name="cx" value="005595287635600419689:mkvbjm66l84"/>
            <input type="text" name="q" placeholder="Google"/>
            <button type="submit"
                    class="pure-button pure-button-primary">搜尋
            </button>
        </form>
    </div>
</div>

</#macro>

<#-- hot rss aside card
     with optional implicit argument `zoneInfo` -->
<#macro rss>
<div class="aside-card">
    <h4>訂閱 RSS</h4>

    <div class="aside-card-box">
        <#if zoneInfo??>
            <a class="plain" href="/z/${zoneInfo.name}/hot.rss"><i
                    class="fa fa-rss-square rss-icon"></i> ${zoneInfo.aliasName} - 熱門</a>
        <#else>
            <a class="plain" href="/hot.rss"><i
                    class="fa fa-rss-square rss-icon"></i> 綜合 - 熱門</a>
        </#if>
    </div>
</div>

</#macro>

kaif-web/src/main/resources/templates/macros/template.ftl
<#import "/spring.ftl" as spring />
<#import "url.ftl" as url />
<#import "util.ftl" as util/>
<#--
sample configs:

1)

<@template.page layout='small'>

2)

// if you use `head` you must define <title>
<#assign head>
    <title>foo zone</title>
    <meta name="description" content="foo zone is best">
</#assign>
<@template.page
    layout='full'
    head=headContent>

3) for error page

<@template.page layout='full' errorPage=true >

-->
<#macro page layout head="" applyZoneTheme=false errorPage=false>

  <!doctype html>
  <html lang="zh-Hant">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <#-- meta data for dart, see ServerType for detail -->
      <#if kaif.profilesActive?contains('dev')>

      <#-- for detect dev mode only, should not leak information to produciton -->
        <meta name="kaifProfilesActive" content="${(kaif.profilesActive)!"prod"}">

      <#-- server locale is only used in dev mode, because the page will be cached for everyone
      -->
        <meta name="kaifLocale" content="${(request.getLocale().toString())!"en_US"}">
      </#if>

    <link rel='stylesheet' href='/webjars/yui-pure/0.5.0/pure-min.css'>
    <link rel='stylesheet' href='/webjars/yui-pure/0.5.0/grids-responsive-min.css'>
    <link rel="stylesheet" href="/webjars/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" href="<@spring.url '/img/favicon.ico' />" type="image/x-icon">

      <#-- less/kaif.less are compiled by dart transformer
        -->
      <#if kaif.profilesActive?contains('dev')>
        <link rel="stylesheet" href="//localhost:15980/less/kaif.css">
      <#else>
        <link rel="stylesheet" href="<@spring.url '/css/kaif.css' />">
      </#if>
      <#if applyZoneTheme>
        <link rel="stylesheet" href="<@spring.url '/css/${zoneInfo.theme}.css' />">
      </#if>
      <#if head?is_string>
        <title>kaif.io</title>
      <#else>
          ${head}
      </#if>

  </head>
  <body>

  <header class="header">
    <div class="container">
      <div class="top-menu pure-menu pure-menu-open pure-menu-horizontal">
        <a class="pure-menu-heading" href="/">
          <img class="logo"
               src="<@spring.url '/img/kaif_white@2x.png'/>"
               alt="kaif"/>
        </a>
        <ul class="pure-menu-children" account-menu>
            <#-- mock
                <li class="pure-menu-can-have-children pure-menu-open">
                    <a class="pure-menu-label" href="#">Top</a>
                    <ul >
                        <li><a href="#">sub 1</a></li>
                        <li><a href="#">sub 2</a></li>
                    </ul >
                </li>
            -->
        </ul>
      </div>
    </div>
  </header>

  <main>
    <div class="container">
        <#if layout == 'small'>
          <div class="pure-g">
            <div class="pure-u pure-u-lg-1-6"></div>
            <div class="pure-u-1 pure-u-lg-2-3 l-box">
                <#nested>
            </div>
            <div class="pure-u pure-u-lg-1-6"></div>
          </div>
        <#elseif layout == 'full'>
        <#-- full layout let nested take full control -->
            <#nested>
        <#else>
            <#nested>
        </#if>
    </div>
  </main>

  <footer class="footer l-box">
    <div class="container">
      <div class="footer-item">
            <span>
                &#169; 2019 All Rights Reserved
            </span>
        <a href="/z/kaif-faq">常見問題</a>
        <a href="/z/kaif-terms">服務條款</a>
        <a href="/developer">開發者</a>
      </div>
    </div>
  </footer>
  <#-- Error page will not enable js, for security reason -->
  <#if !errorPage >
      <#if kaif.profilesActive?contains('dev')>
      <#-- require dart pub serve, please run `cd kaif-fe; ../gradlew webDevServe` -->
        <div id="waitingPubServe"
             style="position: fixed; bottom:0; right:0px; padding: 3px 10px; background-color: rgba(92, 0, 0, 0.67); color:white">
          Waiting Pub Serve...
        </div>
        <script src="//localhost:15980/main.dart.js"></script>
      <#else>
        <script src="<@spring.url '/web/main.dart.js'/>"></script>
      </#if>
  </#if>

  <#-- google analytics -->
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-896ZQFYLS6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-896ZQFYLS6');
  </script>
  </body>
  </html>

</#macro>

<#--
 zone layout
-->
<#macro zone data showMenu=true>

    <#local zoneInfo=data />

  <div class="zone ${zoneInfo.theme}">
      <@zoneHeader/>
      <#if showMenu>
        <nav class="zone-menu pure-menu pure-menu-open pure-menu-horizontal">
            <@util.menuLink '/z/${zoneInfo.name}' '熱門'/>
            <@util.menuLink '/z/${zoneInfo.name}/new' '最新'/>
            <@util.menuLink '/z/${zoneInfo.name}/new-debate' '最新討論'/>
            <@util.menuLink '/z/${zoneInfo.name}/honor' '每月英雄榜'/>
        </nav>
      </#if>
      <#nested/>
  </div>
</#macro>

<#--
  zoneHeader under zone
  -->
<#macro zoneHeader subTitle="">
  <div class="zone-header">
    <div class="zone-title"><a href="<@url.zone data=zoneInfo/>">
        <i class="fa fa-caret-right"></i> ${zoneInfo.aliasName} <@url.zone data=zoneInfo/>
      </a> ${subTitle}</div>
  </div>
</#macro>

<#--
 home layout
-->
<#macro home>

  <div class="home">
    <nav class="home-menu pure-menu pure-menu-open pure-menu-horizontal">
        <@util.menuLink '/' '綜合熱門'/>
        <@util.menuLink '/new' '綜合最新'/>
        <@util.menuLink '/new-debate' '最新討論'/>
        <@util.menuLink '/honor' '每月英雄榜'/>
        <@util.menuLink '/zone/a-z' '所有討論區'/>
    </nav>
      <#nested/>
  </div>
</#macro>

<#--
 user layout
-->
<#macro user username>
  <div class="grid">
    <div class="grid-body">
      <div class="user">
        <nav class="user-menu pure-menu pure-menu-open pure-menu-horizontal">
            <@util.menuLink '/u/${username}' '關於'/>
            <@util.menuLink '/u/${username}/articles' '分享的文章'/>
            <@util.menuLink '/u/${username}/debates' '參與的討論'/>
            <@util.menuLink '/u/${username}/honors' '討論區聲望'/>
        </nav>
          <#nested/>
      </div>
    </div>
    <aside class="grid-aside">
    </aside>
  </div>

</#macro>

kaif-web/src/main/resources/templates/macros/url.ftl
<#import "/spring.ftl" as spring />

<#--
  return current request path (without exist query string)

  for example:

    given current page at /z/programming?abc=def
    the result of <@url.current> is:

       /z/programming

  if you add arguments, it will append to current path (exist query string ignored)

    given current page at /z/programming?abc=def
    the result of <@url.current start=123 end=456> is:

       /z/programming?start=123&end=456

-->
<#macro current params...><#compress>
    <#assign currentUrl = springMacroRequestContext.getRequestUri() />
    <#if (params?size > 0) >
        <#assign currentUrl = currentUrl + '?' />
        <#list params?keys as name>
            <#assign currentUrl = currentUrl + name + '=' + params[name]/>
            <#if name_has_next>
                <#assign currentUrl = currentUrl + '&'/>
            </#if>
        </#list>
    ${currentUrl}
    <#else>
    ${currentUrl}
    </#if>
</#compress></#macro>

<#-- check if current url match input

     includePart=true will treat current path `/foo/bar.part` same as target path `/foo/bar`
  -->
<#function isCurrentPath targetPath includePart=false matchEndSlash=true>
    <#local currentPath = springMacroRequestContext.getRequestUri() />
    <#return currentPath == targetPath
    || (matchEndSlash && (currentPath == targetPath + '/'))
    || (includePart && currentPath == targetPath + '.part') />
</#function>

<#-- zone url,
     data can be ZoneInfo, Article, or Debate -->
<#macro zone data>/z/${data.zone}</#macro>

<#-- article's debate url,
     data can be Article or Debate -->
<#macro article data>/z/${data.zone}/debates/${data.articleId}</#macro>

<#-- debate's permanent url,
     data is Debate -->
<#macro debate data parent=false><#compress>
    <#if parent>
    /z/${data.zone}/debates/${data.articleId}/${data.parentDebateId}
    <#else>
    /z/${data.zone}/debates/${data.articleId}/${data.debateId}
    </#if>
</#compress>
</#macro>

<#-- account's public url, data can be
     Account, Debate (debaterName), Article (article author name) -->
<#macro account data>
    <#compress>
        <#if (data.debaterName)??>
        /u/${data.debaterName}
        <#elseif (data.authorName)??>
        /u/${data.authorName}
        <#else>
        /u/${data.username}
        </#if>
    </#compress>
</#macro>

<#-- implicit variable zoneInfo -->
<#macro createArticleLink><#compress>
    <#if zoneInfo??>
        <#assign prefix='/z/${zoneInfo.name}' />
    <#else>
        <#assign prefix='' />
    </#if>
${prefix}/article/create-link
</#compress>
</#macro>

<#-- implicit variable zoneInfo -->
<#macro createArticleSpeak><#compress>
    <#if zoneInfo??>
        <#assign prefix='/z/${zoneInfo.name}' />
    <#else>
        <#assign prefix='' />
    </#if>
${prefix}/article/create-speak
</#compress>
</#macro>

kaif-web/src/main/resources/templates/macros/util.ftl
<#import "url.ftl" as url />

<#--
 menuLink
-->
<#macro menuLink href name>
<#-- here we have a tricky hack
     the landing page is `/z/programm/article/create`
     but part template is `/z/programm/article/create.part`
     if `create.part` use menuLink, it won't work because the url is not same as
     landing page
     thus we compare both url
  -->
    <#local selected = url.isCurrentPath(href, true) />
<li class="${selected?string('pure-menu-selected','')}"><a href="${href}">${name}</a></li>
</#macro>

<#function abbreviate str max>
    <#if str?? >
        <#if str?length <= max>
            <#return str />
        <#else>
            <#return str?substring(0, max)  + '...'/>
        </#if>
    <#else >
        <#return ''/>
    </#if>
</#function>

<#--
 show relative time of Instant. the output is wrapped by html5 time tag
 -->
<#macro time instant maxUnit=""><#compress>
<time datetime="${instant}">
    <#if maxUnit?has_content>
        ${relativeTime(instant, maxUnit)}
    <#else>
    ${relativeTime(instant)}
    </#if>
</time>
</#compress>
</#macro>

<#macro bookmarklet>
<div class="bookmarklet">
    <h3>貼文小幫手: Bookmarklet</h3>

    <p>你可以使用 Bookmarket 一鍵完成分享文章！</p>

    <p>安裝：將下面的連結拖拉瀏覽器的書簽列</p>

    <div class="bookmarklet-container">
        <i class="fa fa-caret-right"></i>
        <a class="bookmarklet-link" rel="nofollow"
           href="javascript:window.location=%22https://kaif.io/article/create-link?c=%22+encodeURIComponent(document.location)+%22&t=%22+encodeURIComponent(document.title)">
            分享到 Kaif
        </a>
        <i class="fa fa-caret-left"></i>
    </div>
    <p>以後看到你覺得很棒的網頁，直接點書簽列上的 <strong style="white-space: nowrap">[ 分享到 Kaif ]</strong> 鈕即可。</p>
</div>
</#macro>